site_name: 'show_CSS_examples'
nav:
  - Home:
    - Home: home/home.md
  - Documentation:
    - Documentation: documentation/documentation.md
  - Introduction to CSS:
    - Introduction: css/00-intro.md
    - Lab 1: css/01-lab.md
    - Lab 2: css/02-lab.md
    - Lab 3: css/03-lab.md
    - Lab 4: css/04-lab.md
    - Lab 5: css/05-lab.md
    - Lab 6: css/06-lab.md
    - Lab 7: css/07-lab.md
  - Getting Started:
    - Getting Started: getting-started/getting-started.md
  - Support:
    - Support: support/support.md
    - Team: support/team.md
    - Contact: support/contact.md

repo_name: 'show_CSS_examples'
repo_url: 'https://github.optum.com/kstaple3/show_CSS_examples'
edit_uri: 'blob/master/docs'
copyright: 'Copyright &copy; 2020 Optum'
theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'blue'
  feature:
    tabs: true
  custom_dir: 'theme'
  favicon: img/favicon.ico
  logo: img/optum-white.png
  font:
    text: Arial
    code: Roboto Mono
extra_css:
  - styles/optum-theme.css
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
