site_name: 'CoderDojo TC Web-UX'
nav:
  - CoderDojo TC: https://coderdojotc.github.io/CoderDojoTC/
  - Home: index.md
  - Intoduction to HTML:
    - Introduction: intro-to-html/01-intro.md
    - Elements and Attributes: intro-to-html/01a-elements-and-attributes.md
    - HTML File Structure: intro-to-html/02-html-structure.md
    - Headings: intro-to-html/03-headings.md
    - Bold and Italic: intro-to-html/04-bold-and-italic.md
    - Lists: intro-to-html/05-lists.md
    - Images: intro-to-html/06-images.md
    - Links: intro-to-html/07-links.md
    - Tables: intro-to-html/08-tables.md
    - Forms: intro-to-html/09-forms.md
  - Web Drawing with SVG:
    - Introduction: svg/01-intro.md
    - Circle: svg/02-circle.md
    - Line: svg/03-line.md
    - Rectangle: svg/04-rectangle.md
    - Ellipse: svg/05-ellipse.md
    - Polygon: svg/06-polygon.md
    - Polyline: svg/07-polyline.md
    - Path: svg/08-path.md
  - Learning Objectives: learning-objectives.md
  - Resources: resources.md
  - Contact: contact.md

site_description: 'Resources for teaching Web and UX to CoderDojo Twin Cities students.'
site_author: 'Dan McCreary'
repo_name: 'web-ux'
repo_url: 'https://github.com/CoderDojoTC/web-ux'
edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/coderdojo-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  feature:
    tabs: true
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
plugins:
    - search
markdown_extensions:
