site_name: 'CoderDojo TC Web-UX'
nav:
  - CoderDojo TC: https://coderdojotc.github.io/CoderDojoTC/
  - Home: index.md
  - Introduction to UX:
    - Introduction: ux/01-intro.md
    - What is UX: ux/02-what-is-ux.md
    - User Research: ux/03-user-research.md
    - Personas: ux/04-personas.md
    - Information Architecture: ux/05-information-architecture.md
    - Wireframing.md: ux/06-wireframing.md
    - Design Thinking: ux/07-design-thinking.md
    - Sketching: ux/08-sketching.md
    - User Interface Design: ux/09-user-interface-design.md
    - Web Design: ux/10-web-design.md
    - Mobile Design: ux/11-mobile-design.md
    - Voice Design: ux/12-voice-design.md
  - Intoduction to HTML:
    - Introduction: intro-to-html/01-intro.md
    - Elements and Attributes: intro-to-html/01a-elements-and-attributes.md
    - HTML File Structure: intro-to-html/02-html-structure.md
    - Headings: intro-to-html/03-headings.md
    - Bold and Italic: intro-to-html/04-bold-and-italic.md
    - Lists: intro-to-html/05-lists.md
    - Images: intro-to-html/06-images.md
    - Links: intro-to-html/07-links.md
    - Tables: intro-to-html/08-tables.md
    - Forms: intro-to-html/09-forms.md
  - Introduction to CSS:
    - Introduction: css/00-intro.md
    - Font Color: css/01-font-color.md
    - Key Idea- Applying Style: css/02-applies-style-to-indicated-elements.md
    - Font and Font Families: css/03-font-and-font-families.md
    - Styling by Class: css/04-styling-by-class.md
    - CSS Selectors: css/05-css-selectors.md
    - Combining CSS Selectors: css/06-combining-css-selectors.md
    - Styling based on State: css/07-styling-based-on-state.md
    - Types of CSS: css/08-types-of-css.md
  - Introduction to Javascript:
    - Introduction: intro-to-javascript/01-introduction.md
    - Variables: intro-to-javascript/02-variables.md
    - Operators: intro-to-javascript/03-operators.md
    - Conditionals: intro-to-javascript/04-conditionals.md
    - Functions: intro-to-javascript/05-functions.md
    - Events: intro-to-javascript/06-events.md
    - Bring it all together: intro-to-javascript/07-bringing-it-together.md
  - Web Drawing with SVG:
    - Introduction: svg/01-intro.md
    - Circle: svg/02-circle.md
    - Line: svg/03-line.md
    - Rectangle: svg/04-rectangle.md
    - Ellipse: svg/05-ellipse.md
    - Polygon: svg/06-polygon.md
    - Polyline: svg/07-polyline.md
    - Path: svg/08-path.md
  - Introduction to Bootstrap:
    - Introduction: intro-to-bootstrap/01-intro.md
    - Getting Started: intro-to-bootstrap/02-getting-started.md
    - Containers: intro-to-bootstrap/03-containers.md
    - Grids: intro-to-bootstrap/04-intro-to-grids.md
    - Typography: intro-to-bootstrap/05-typography.md
    - Buttons: intro-to-bootstrap/06-buttons.md
    - Forms: intro-to-bootstrap/07-forms.md
    - Modals: intro-to-bootstrap/08-modals.md
  - Learning Objectives: learning-objectives.md
  - Resources: resources.md
  - Contact: contact.md

site_description: 'Resources for teaching Web and UX to CoderDojo Twin Cities students.'
site_author: 'Dan McCreary'
repo_name: 'web-ux'
repo_url: 'https://github.com/CoderDojoTC/web-ux'
edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/coderdojo-logo.jpg
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  feature:
    tabs: true
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
plugins:
    - search
